### ISSUE TITLE
Does not work on 1.14.4

### ISSUE THREAD

**Issue by Cubxity** [JohnnyJayJay/spigot-maps#3]
**Describe the bug**
An exception was thrown when running createItemStack()

**To Reproduce**
1. Call RenderedMap#createItemStack

**Expected behavior**
It should return an item stack

**Screenshots, Code & Stack Traces**
```java
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_14_R1.inventory.CraftMetaItem cannot be cast to org.bukkit.inventory.meta.MapMeta
	at com.github.johnnyjayjay.spigotmaps.RenderedMap.createItemStack(RenderedMap.java:208) ~[?:?]
	at com.github.johnnyjayjay.spigotmaps.RenderedMap.createItemStack(RenderedMap.java:196) ~[?:?]
```

**Spigot Version:** Paper 1.14.4

**Comment by JohnnyJayJay** [comment]
Thank you, I was not aware of that change in 1.14.4 and will look into it.
